name: tesseract # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tesseract Ignition
description: |
  This current contains the Tesseract Setup Wizard.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

# This is only available in snap verions 4.0 and greater
package-repositories:
  - type: apt
    deb-types: [deb]
    components: [main]
    suites: [$SNAPCRAFT_APT_RELEASE]
    key-id: D2486D2DD83DB69272AFE98867170598AF249743
    url: http://packages.osrfoundation.org/gazebo/ubuntu-stable

  - type: apt
    deb-types: [deb]
    components: [main]
    suites: [$SNAPCRAFT_APT_RELEASE]
    key-id: D2486D2DD83DB69272AFE98867170598AF249743
    url: http://packages.osrfoundation.org/gazebo/ubuntu-prerelease

build-packages:
  - software-properties-common
  - dirmngr
  - wget
  - lsb-release
  - gnupg

parts:
  get-ignition:
    plugin: nil
    build-packages:
      - libignition-common3-dev
      - libignition-tools-dev
      - libignition-math6-eigen3-dev
      - libignition-cmake2-dev
      - libignition-plugin-dev
      - libignition-transport8-dev
      - libsdformat9-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libprotoc-dev
      - libglew-dev
      - libfreeimage-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libogre-1.9-dev
      - libogre-2.1-dev
      - ruby-full
    stage-packages:
      - libignition-common3-dev
      - libignition-tools-dev
      - libignition-math6-eigen3-dev
      - libignition-cmake2-dev
      - libignition-plugin-dev
      - libignition-transport8-dev
      - libsdformat9-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libprotoc-dev
      - libglew-dev
      - libfreeimage-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libogre-1.9-dev
      - libogre-2.1-dev
      - ruby-full

  tesseract-workspace:
    plugin: catkin
    source: .
    catkin-packages:
      - tesseract_ignition
      - tesseract
      - tesseract_collision
      - tesseract_common
      - tesseract_environment
      - tesseract_geometry
      - tesseract_kinematics
      - tesseract_scene_graph
      - tesseract_support
      - tesseract_urdf
      - tesseract_visualization
      - opw_kinematics
      - descartes_light
      - bullet3
      - fcl
      - libccd
      - ignition_gui
      - ignition_msgs
      - ignition_sensors
      - ignition_rendering
    include-roscore: false
    recursive-rosinstall: false
    rosinstall-files: [snap/local/ignition_snap.rosinstall]
    after: [get-ignition]
    build-packages:
      - libeigen3-dev
      - libboost-program-options-dev
      - libpcl-dev
      - liboctomap-dev
      - git
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
    stage-packages:
      - libaec0
      - libcurl3-gnutls
      - libhdf5-100
      - libjbig0
      - libjpeg-turbo8
      - libnetcdf-c++4
      - libnetcdf13
      - liboctomap1.8
      - libopenni0
      - libopenni2-0
      - libpcl-common1.8
      - libpcl-io1.8
      - libsz2
      - libtiff5
      - libtinyxml2.6.2v5
      - libusb-1.0-0
      - libvtk6.3

#  stage:
#    # stage everything EXCEPT (note the minuses that make this a blacklist)
#    - -usr/include/my/headers/

apps:
  tesseract-setup-wizard:
    extensions:
      - kde-neon
    environment:
      IGN_GUI_PLUGIN_PATH: $SNAP/opt/ros/melodic/lib/
      IGN_RENDERING_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/
    command: opt/ros/melodic/bin/demo_window
